### ISSUE TITLE
Lack of proxy support

### ISSUE THREAD

**Issue by jose-cardoso** [vmware/tdnf#13]
Unable to use TDNF behind a proxy despite having configured the correct proxy setting in /etc/tdnf/tdnf.conf and via environment variables.

Proxy support exists in DNF so a little surprised TDNF is missing it.

**Comment by ppadmavilasom** [comment]
@jose-cardoso: confirmed missing proxy conf. Will fix and update.

**Comment by ppadmavilasom** [comment]
@jose-cardoso: Updated in dev fork. Would you mind testing this from the https://github.com/ppadmavilasom/tdnf ?

**Comment by jose-cardoso** [comment]
Tested as requested and confirmed as working. Thank you.

Looking forward to an ISO update with this new build included!
