### ISSUE TITLE
tdnf not working | Error 1621 : Is a directory

### ISSUE THREAD

**Issue by agenttank** [vmware/tdnf#133]
what do?

root@photon8 [ /home/stefan ]# tdnf upgrade
Error(1621) : Is a directory
root@photon8 [ /home/stefan ]# tdnf check-local
Error(1621) : Is a directory
root@photon8 [ /home/stefan ]# tdnf check-update
Error(1621) : Is a directory
root@photon8 [ /home/stefan ]# tdnf clean
Error(1621) : Is a directory
root@photon8 [ /home/stefan ]# tdnf info
Error(1621) : Is a directory

journalctl doesn't tell me anything
photonOS was installed only around 2 weeks ago. i didn't do any hacking, only installed 4 docker containers and installed docker-compose by moving their binary into /usr/local/bin/docker-compose

Linux photon8 4.19.115-1.ph3-esx #1-photon SMP Tue Apr 21 18:54:09 UTC 2020 x86_64 GNU/Linux

**Comment by keerthanakalyan** [comment]
Can you try removing the cache directory and try makecache again?
`rm -rf /var/cache/tdnf/*;
tdnf makecache`
What version of photon-repos and tdnf do you use?

**Comment by agenttank** [comment]
removing the cache and makecache did help! great!

root@photon8 [ /var/log ]# tdnf --version
tdnf: 2.1.0

how do i check the version of photon-repos? the files in /etc/yum.repos tell me this

`[photon-debuginfo]
name=VMware Photon Linux debuginfo $releasever ($basearch)
baseurl=https://packages.vmware.com/photon/$releasever/photon_debuginfo_$releasever_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=0
skip_if_unavailable=True
[photon-extras]
name=VMware Photon Extras $releasever ($basearch)
baseurl=https://packages.vmware.com/photon/$releasever/photon_extras_$releasever_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True
[photon-iso]
name=VMWare Photon Linux ISO $releasever ($basearch)
baseurl=file:///mnt/cdrom/RPMS
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=0
skip_if_unavailable=True
[photon]
name=VMware Photon Linux $releasever ($basearch)
baseurl=https://packages.vmware.com/photon/$releasever/photon_release_$releasever_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True
[photon-updates]
name=VMware Photon Linux $releasever ($basearch) Updates
baseurl=https://packages.vmware.com/photon/$releasever/photon_updates_$releasever_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True`

**Comment by keerthanakalyan** [comment]
`tdnf list photon-repos`

**Comment by agenttank** [comment]
`photon-repos.noarch                                             3.0-5.ph3                              @System
photon-repos.noarch                                             3.0-3.ph3                       photon-updates
photon-repos.noarch                                             3.0-4.ph3                       photon-updates
photon-repos.noarch                                             3.0-5.ph3                       photon-updates
photon-repos.noarch                                             3.0-2.ph3                               photon`

**Comment by 0xba1a** [comment]
@keerthanakalyan Can you please give me some background about this issue? 1. Like why the cache directory left unclean? 2. Is this error made more readable in future tdnf releases? 3. Will `tdnf clean all` help here instead of manually deleting the directory?

**Comment by keerthanakalyan** [comment]
This issue has been fixed in latest releases. Also few other clean command issues has been fixed by @oliverkurth. You can use tdnf clean all command instead of manual delete. Please consume latest release.
