### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by Conan-Kudo** [vmware/tdnf#135]
There are significant fixes unreleased in tdnf, and I don't want to have cherry pick ~20-ish commits to make things work well. Can we please have a new release?

**Comment by ppadmavilasom** [comment]
@keerthanakalyan @sshedi https://github.com/vmware/tdnf/releases/tag/v2.1.0 is well tested. can we please release ?

**Comment by Conan-Kudo** [comment]
@ppadmavilasom @keerthanakalyan @sshedi I need a release newer than 2.1.0. That release is missing several fixes.

**Comment by keerthanakalyan** [comment]
@Conan-Kudo We are planning a release. We will release it as soon as possible.

**Comment by keerthanakalyan** [comment]
@Conan-Kudo : We have a new release v2.1.1 https://github.com/vmware/tdnf/releases/tag/v2.1.1
