### ISSUE TITLE
Does not handle multiple packages for install specified on command line

### ISSUE THREAD

**Issue by hickeng** [vmware/tdnf#14]
Found when running in a docker container based of vmware/photon. All but the first package specified for install are ignored, not installed yet the command returns success.:

Step 3 : RUN tdnf install -y grep gawk docker
 ---> Running in 130c8f7412e3
Installing:
 grep   x86_64  2.21-1
Downloading 223390.00 of 223390.00
Testing transaction
Running transaction
 ---> 1e560ccfbc85
Removing intermediate container 130c8f7412e3

tdnf should either install all of the packages or return a usage error when multiple packages are specified.

**Comment by ppadmavilasom** [comment]
Fix by 1.0.5

**Comment by ppadmavilasom** [comment]
Fixed. Handles multiple packages for all alter paths - install, erase, update, reinstall. Fix available from v1.0.7
