### ISSUE TITLE
tdnf should support installing from HTTP and HTTP GPG keys

### ISSUE THREAD

**Issue by voor** [vmware/tdnf#151]
Currently `tdnf` will fail if it tries to install from a URL provided package, for example:

```
tdnf install -y http://example.com/example.rpm
```

I would expect this to work.

Additionally, GPG files in `.repo` files are required to be files, and cannot be provided as URLs.

Copied from https://github.com/vmware/photon/issues/1017
Somewhat related to https://github.com/vmware/tdnf/issues/77 except URL instead of a local file.

**Comment by melck** [comment]
It will be perfect if multi gpg keys are supported as well. Ggp keys be separated with a space or comma. Ex: [Installation of `kubeadm`](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl).

**Comment by oliverkurth** [comment]
Remote keys are now supported with merged PR https://github.com/vmware/tdnf/pull/171 . Multiple keys are in pending PR https://github.com/vmware/tdnf/pull/179 . Installing RPMs from command line (file or URL) is in pending PR https://github.com/vmware/tdnf/pull/175 .

**Comment by oliverkurth** [comment]
This is done, all related PRs are merged.
