### ISSUE TITLE
How to download a package and its dependencies without install it?

### ISSUE THREAD

**Issue by lynic** [vmware/tdnf#153]
Hi, I would like to download a package with its dependencies and build a local repo, how can I do that with tdnf? Is there any command like `dnf download` ?

**Comment by keerthanakalyan** [comment]
you can build a local repo by downloading the RPMs using curl / wget command. Please refer this https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/adding-a-new-repository.html

However we do not ```tdnf download <URL to rpm>``` support in tdnf.

**Comment by oliverkurth** [comment]
I think we would need a `--downloadonly` option, together with `--downloaddir` like dnf has them.

**Comment by oliverkurth** [comment]
This is addressed with https://github.com/vmware/tdnf/commit/99971a31c899a87fc3f1f7d7013f3ab653ad609b .
