### ISSUE TITLE
Error when installing into a btrfs root

### ISSUE THREAD

**Issue by daandemeyer** [vmware/tdnf#154]
I've been trying to add photon linux to [mkosi](https://github.com/systemd/mkosi.git)'s continuous integration setup. This is working quite well, except for the build that installs photon into a gpt btrfs image where tdnf fails with `Error(4294967295) : Unknown error -1601`, as well as `/sbin/ldconfig: no such file or directory` errors when installing packages.

This only happens on btrfs and only with tdnf so I'm inclined to think the bug might be in tdnf. I'm not sure where to start looking though. To try and reproduce locally, the following commands can be executed (assuming tdnf,btrfs-progs,e2fsprogs and maybe dosfstools are installed):

```sh
git clone https://github.com/DaanDeMeyer/mkosi.git --branch ci-tdnf
cd mkosi
sudo ./mkosi --distribution photon --format gpt_btrfs --debug run -f build
```

A link to a failed run: https://github.com/systemd/mkosi/runs/935891127?check_suite_focus=true#step:8:519. (Github Actions doesn't handle output on both stdout/stderr very well. The line I linked is the last line produced by tdnf. If you scroll further down you can see the commands executed by mkosi before running tdnf)

**Comment by daandemeyer** [comment]
I've attached an strace log of tdnf on Github Actions if that helps in figuring out the issue.

[tdnf.zip](https://github.com/vmware/tdnf/files/5025203/tdnf.zip)

**Comment by oliverkurth** [comment]
Looks CI runs for Photon and a few others have been dropped a while ago: https://github.com/systemd/mkosi/commit/0f167a2205070096e182222a84ddc954a6c23997#diff-87ee5504a3e25ac558b343724c905f2f7949e8cec3d92b9c4300bb922afa164f

**Comment by oliverkurth** [comment]
Let's close this. `tdnf` does not care about the filesystem used, and we don't have enough information to debug this. We can always re-open if this continues to be an issue.
