### ISSUE TITLE
Add option to disable SSL verification of repo baseurl

### ISSUE THREAD

**Issue by sidcha** [vmware/tdnf#169]
When option `sslverify` is set to 0, we must skip SSL verification of the repo base URL.

Needed-By: https://github.com/vmware/photon/issues/384

**Comment by oliverkurth** [comment]
I think this is addressed with https://github.com/vmware/tdnf/pull/176 ?

**Comment by oliverkurth** [comment]
Fixed with https://github.com/vmware/tdnf/pull/176
