### ISSUE TITLE
tdnf install returns error 137 if package is installed

### ISSUE THREAD

**Issue by mattolenik** [vmware/tdnf#22]
I'm installing prereqs with tdnf with containers running the Photon base image, and several times I've had my build break because new packages were introduced into the base image that I used to install in my scripts. E.g. I used to say "tdnf install -y grep" but now that fails because grep already exists. I think tdnf should work like other package managers and return 0 for "nothing to do" rather than an error. Generally a no-op install would not be considered an error.

**Comment by ppadmavilasom** [comment]
Agree. Should fix by 1.0.4

**Comment by ppadmavilasom** [comment]
Fixed in 1.0.4 - If installed and of the same version, there is no error. If installed and a newer version is available, will be updated (with -y)

**Comment by ppadmavilasom** [comment]
Not fixed. Should be in by 1.0.5 together with tests.

**Comment by ppadmavilasom** [comment]
Resolved. Added tests for the same.
