### ISSUE TITLE
TDNF printing retrying 1/10...10/10 and resulting in multiple error codes in case we have network error

### ISSUE THREAD

**Issue by tapakund** [vmware/tdnf#226]
TDNF printing retrying 1/10...10/10(i think we should not print this retrying in console)  and resulting in multiple error codes in case we have network error. Attached a screenshot of the same.

<img width="1407" alt="Screenshot 2021-03-04 at 3 58 30 PM" src="https://user-images.githubusercontent.com/39723251/109950459-87ff6380-7d02-11eb-957f-0fd40bdba332.png">

**Comment by oliverkurth** [comment]
We discussed this internally, and some issues have been addressed. I think we can close this. Reopen if you disagree.
