### ISSUE TITLE
Add History and rollback support

### ISSUE THREAD

**Issue by paulneumeyer** [vmware/tdnf#241]
I'm would like to use the history functionality (history list, history undo) that is available in yum and dnf, but as far as I can tell, it is not in tdnf.  

Is work planned or currently underway to implement that functionality?  Alternatively is a plugin available for this from a third party?

**Comment by oliverkurth** [comment]
No, we do not have that feature, and there is no plugin. Some kind of history would be needed if we want to implement the 'autoremove' feature, see issues #81  and #187 .

**Comment by oliverkurth** [comment]
This is being worked on in PR #314 . The `autoremove` feature is implemented already.

**Comment by oliverkurth** [comment]
PR #314 is merged, closing this.

Note that there are a few outstanding issuers regarding autoinstalled packages which will be addressed in PR #327 .
