### ISSUE TITLE
tdnf makecache is crashing

### ISSUE THREAD

**Issue by tapakund** [vmware/tdnf#265]
➜  yum.repos.d cat Artifactory.repo
[Artifactory] name=Artifactory baseurl=https://packages.vmware.com/photon/$releasever/photon_debuginfo_$releasever_$basearch enabled=0 gpgcheck=0
➜  ~ tdnf makecache
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64) Updates'
Refreshing metadata for: 'Test repo'      3581   100%
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64)'
[1]    9745 segmentation fault (core dumped)  tdnf makecache
➜  ~ echo $?
139
➜  ~ rpm -qa  tdnf
tdnf-3.1.4-2.ph3.x86_64
➜  ~

(gdb) n
230	    for(pRepo = pTdnf->pRepos; pRepo; pRepo = pRepo->pNext)
(gdb) n
234	        if ((strcmp(pRepo->pszName, "@cmdline") == 0) ||
(gdb) p pRepo->pszName <-- This is NULL which we are sending to strcmp causing the segmentation fault.
$14 = 0x0

**Comment by oliverkurth** [comment]
I think this is fixed with 25fef2f4ec5916c6e7c50ebb3c54489466044bba.
