### ISSUE TITLE
TDNFAddCmdLinePackages fails when a file or symlink exists with same name as package name

### ISSUE THREAD

**Issue by LaurentChardon** [vmware/tdnf#270]
When a file or link is present in the working directory, with the same name as the package name in the cli arguments, tdnf aborts. Here is an example that works normaly:

```
[sgugshell root@octane ~]# tdnf search irix  
libdicl : Dans Irix Compatibility Library
microdnf : Minimal C implementation of DNF tweaked for IRIX
chrpath : Modify rpath of compiled programs
libdicl : Dans Irix Compatibility Library
microdnf : Minimal C implementation of DNF tweaked for IRIX
glew : The OpenGL Extension Wrangler Library
libGL : Irix OpenGL library
libdicl : Dans Irix Compatibility Library
microdnf : Minimal C implementation of DNF tweaked for IRIX
```

The following is less normal:

```
[sgugshell root@octane ~]# touch irix
[sgugshell root@octane ~]# tdnf search irix
Error(1622) : Invalid argument
```

This is due to a check for an existing file or symlink with the same name as the package name in `client/api.c`, where `TDNFAddCmdLinePackages` checks each package name. There are no comments in that region of the code, so I'm not sure what this test is supposed to protect.

**Comment by oliverkurth** [comment]
Thanks for reporting.

The reason for the check is for installing local packages. For example, you could have downloaded or built an rpm and then want to install it using tdnf (which would then install dependencies for you, if any). Example:
```
curl -O http://some.site/foo-1.2.3-4.rpm
tdnf install foo-1.2.3-4.rpm
```
Probably the check could be more sophisticated, maybe we should check the extension of the filename or symlink, and only allow if it matches `*.rpm`.
