### ISSUE TITLE
Check for available size before download/install

### ISSUE THREAD

**Issue by ppadmavilasom** [vmware/tdnf#34]
@YustasSwamp reports this. Check for available size before download/install and throw appropriate errors if not enough space to perform action.

**Comment by oliverkurth** [comment]
There are two issues to address:
* space for downloading the package before doing the download. We can just check the space for the partition where we store the downloads (`/var/tdnf/cache` unless configured differently).
* space for the actual install. This can be tricky if there are multiple partitions involved.

**Comment by prestonsn** [comment]
PR https://github.com/vmware/tdnf/pull/321 provides a cache directory space check. However, it does not address a potential out of disk space error during RPM installs.

**Comment by oliverkurth** [comment]
I think we can close this. The first item is addressed. The second is actually also addressed - it will be detected by the rpm backend, when the transaction is attempted.
