### ISSUE TITLE
multipackage install error handling - skip-broken or strict option

### ISSUE THREAD

**Issue by Rob-Wal** [vmware/tdnf#342]
### Is your feature request related to a problem? Please describe.

I have search through all the documentation and issues and cannot find the equivalent of --skip-broken or --setopt=strict=0 for tdnf.  When trying to install multiple packages with one missing the entire command fail. I receive error 1011.
eg:
[root@PHT4-Docker01 [ ~ ]# tdnf install zip unzip foo p7zip bash
foo package not found or not installed
Error(1011) : No matching packages

### Describe the solution you'd like

implement DNF strict option like --skip-broken or option strict.
https://dnf.readthedocs.io/en/latest/cli_vs_yum.html#skip-broken

### Describe alternatives you've considered

writing custom bash install script instead of a oneliner.

### Additional context
Base photon OVA rev2.
Name        : photon-release
Version     : 4.0
Release     : 2.ph4
Architecture: noarch
Install Date: Wed 12 Jan 2022 01:27:01 PM EST
Group       : System Environment/Base
Size        : 3388
License     : Apache License
Signature   : RSA/SHA1, Tue 09 Nov 2021 11:34:31 PM EST, Key ID c0b5e0ab66fd4949
Source RPM  : photon-release-4.0-2.ph4.src.rpm
Build Date  : Tue 09 Nov 2021 09:52:59 PM EST
Build Host  : photon-616a4c2
Vendor      : VMware, Inc.
URL         : https://vmware.github.io/photon/
Summary     : Photon release files
Description :
Photon release files such as yum configs and other /etc/ release related files

Name        : tdnf
Version     : 3.3.1
Release     : 1.ph4
Architecture: x86_64
Install Date: Thu 18 Aug 2022 11:56:56 AM EDT
Group       : Applications/RPM
Size        : 350916
License     : LGPLv2.1,GPLv2
Signature   : RSA/SHA256, Fri 03 Jun 2022 11:32:26 PM EDT, Key ID c0b5e0ab66fd4949
Source RPM  : tdnf-3.3.1-1.ph4.src.rpm
Build Date  : Fri 03 Jun 2022 10:56:09 PM EDT
Build Host  : photon-616a4c2
Vendor      : VMware, Inc.
URL         : https://github.com/vmware/tdnf
Summary     : dnf/yum equivalent using C libs
Description :
tdnf is a yum/dnf equivalent which uses libsolv and libcurl

**Comment by oliverkurth** [comment]
Thanks for the suggestion, sorry for replying late - I was on a vacation.

I am looking into this.
