### ISSUE TITLE
Error while compiling with cmake

### ISSUE THREAD

**Issue by Bezkup** [vmware/tdnf#347]
### Describe the bug

cmake has failed with 
```
--   Package 'rpm', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  CMakeLists.txt:59 (pkg_check_modules)
```
but rpm exists
```
dnf info rpm
Installed Packages
Name         : rpm
Version      : 4.17.1
Release      : 3.fc36
```
What can I do to resolve?

### Reproduction steps

1. clone the repository
2. cd tdnf
3. mkdir build && cd build
4. cmake ..

### Expected behavior

It should make the make file

### Additional context

I'm a newbie in fedora, maybe i did something wrong?

**Comment by oliverkurth** [comment]
You need the `rpm-devel` package, which includes the header files (and others) needed to build with the rpm libraries. If you install all packages that are installed in this Dockerfile: https://github.com/vmware/tdnf/blob/dev/ci/Dockerfile.fedora you should be covered:
```
RUN dnf -y install gcc make cmake libcurl-devel rpm-devel rpm-build \
        libsolv-devel popt-devel sed createrepo_c glib2-devel libxml2 \
        findutils python3-pytest python3-requests python3-urllib3 \
        python3-pyOpenSSL python3 python3-devel valgrind gpgme-devel \
        libxml2-devel openssl-devel sqlite-devel rpm-sign which python3-pip \
        shadow-utils sudo e2fsprogs util-linux
```

**Comment by Bezkup** [comment]
Yes! Thank you, it worked!
