### ISSUE TITLE
metalink plugin uses wrong checksum for verification

### ISSUE THREAD

**Issue by oliverkurth** [vmware/tdnf#373]
### Describe the bug

A metalink file can have multiple checksums. If I understand correctly, these can be tried in order. For example, this is the file for current Fedora 37:
```
<?xml version="1.0" encoding="utf-8"?>
<metalink version="3.0" xmlns="http://www.metalinker.org/" type="dynamic" pubdate="Tue, 22 Nov 2022 00:01:23 GMT" generator="mirrormanager" xmlns:mm0="http://fedorahosted.org/mirrormanager">
 <files>
  <file name="repomd.xml">
   <mm0:timestamp>1668992591</mm0:timestamp>
   <size>8307</size>
   <verification>
    <hash type="md5">d7338c528c9612025dddd74e4467c0e6</hash>
    <hash type="sha1">bdf0de43e3551855d42af6f6a5eac4552ed20ca7</hash>
    <hash type="sha256">c096acb14db2b66ef4f696db98e7a64cdfa5cd8f251bc34998e767346515e620</hash>
    <hash type="sha512">b4e08a810afad386776ebb7f96e6b765c1f27a596776d0d3ac2e793f6139f5635e1ec6af5f8068b8e7c2ed064cf9509c3d837b43f373dee48d0bdb99ffc33356</hash>
   </verification>
   <mm0:alternates>
    <mm0:alternate>
      <mm0:timestamp>1668906925</mm0:timestamp>
      <size>8307</size>
      <verification>
       <hash type="md5">d74c5f729e207da802ce4c1b84d37f1c</hash>
       <hash type="sha1">30d4806e87ffbe6438373065b3184d3c615a5aa3</hash>
       <hash type="sha256">00d4d4cdbe19d238dd5b01dcd009b46fb692101c9b306044a4efcb0f56297961</hash>
       <hash type="sha512">914c3722e2b6826379d8ef2772b8d2fad6a2c4238bba58edd58875b579cfa5226b6f5517f05eada400737ef9d40490c49a52f697d53bb26713b7176ec90d2799</hash>
      </verification>
    </mm0:alternate>
    <mm0:alternate>
      <mm0:timestamp>1668825721</mm0:timestamp>
      <size>8304</size>
      <verification>
       <hash type="md5">54cb1f85848092bcdb15f444cab218f1</hash>
       <hash type="sha1">3ac34a6f871c99b5161b7aa7b23294085e7565be</hash>
       <hash type="sha256">69eca52a66ac7def820baf82ca8c1a914d20039555bd336deb3fa36d52fc28e4</hash>
       <hash type="sha512">cae42f8170b787d255c9f971058af5ad26159aab36b97c5b2f2cb883fd18cab61fdbc070061d834b329a9127026b53145d53437af57af896db233829487edcbb</hash>
      </verification>
    </mm0:alternate>
   </mm0:alternates>
```
Note the checksums under `<verification>` directly under `<file>` and then under `<alternate>`. It looks like the metalink plugin uses the last alternate, in this case `cae42f8170b787d255c9f971058af5ad26159aab36b97c5b2f2cb883fd18cab61fdbc070061d834b329a9127026b53145d53437af57af896db233829487edcbb` for `sha512`. However, this refers to older versions of `repomd.xml`. Verifivation will fail if we download an updated version.

Ideally, the plugin should verify against all available checksums.

### Reproduction steps

We actually just need a metalink file with alternate checksums as above. But I found this while trying tdnf for Fedora.

1. Build tdnf in Fedfora 37
2. make install
3. Add `/usr/locallib64` to library search path:
`echo /usr/local/lib64/>>/etc/ld.so.conf && ldconfig`
5. Enable plugins:
```
echo plugins=1 >> /etc/tdnf/tdnf.conf
echo pluginpath=/usr/local/lib64/tdnf-plugins >> /etc/tdnf/tdnf.conf
```
6. Try a tdnf command, for example `tdnf list --installed`
7. Observe the error:

```tdnf list --installed
Loaded plugin: tdnfrepogpgcheck
Loaded plugin: tdnfmetalink
Refreshing metadata for: 'Fedora 37 - x86_64 - Updates'
Error: Validating metalink (/var/cache/tdnf/updates-fd4d3d0d/tmp/repomd.xml) FAILED (digest mismatch)
Error: TDNFCheckRepoMDFileHash 2501
Plugin error: metalink plugin error: (null)

Error(2501) : Checksum Validation failed for the repomd.xml downloaded using URL from metalink
Error: Failed to synchronize cache for repo 'Fedora 37 - x86_64 - Updates'
Error(2501) : Checksum Validation failed for the repomd.xml downloaded using URL from metalink
```

### Expected behavior

Successful metadata download.

### Additional context

Ideally, in the case of a failed checksum match, the plugin should also attempt to download the metadata using one of the other URLs. This would require a small architectural change.

**Comment by ntsbtz** [comment]
@oliverkurth It is checking for all the checksum not only the last one. So when it starts lets have an example of above metalink file.
So first it will check for md5 and if its a valid checksum it will store into the context. Next it will check for sha1 now it will give the priority to sha1 and if its valid it will update the stored hash context. Like this if next one is sha256 and its valid it will update the context.

Now the problem is if sha512 is the next valid checksum then the context will be updated. And the next checksum is again sha512 and its a valid checksum than hash context store this one.

After checking all the hashlist we have the checksum with highest priority . And now we are going to validate the checksum against the repomd.xml file which is causing the issue. Because the checksum is not going to match here as the first sha512 was the right checksum for this file.

so we have couple of solution for this lets discuss.

**Comment by oliverkurth** [comment]
I made a fix here: https://github.com/vmware/tdnf/pull/374. The actual fix is in this commit: https://github.com/vmware/tdnf/pull/374/commits/5196eca2c59d69c0884c601b2653b157307ed7f9 . The code now finds the best checksum type and the tests all of that type.
