### ISSUE TITLE
after restore of  8 month old vm tdnf update broken

### ISSUE THREAD

**Issue by hanscees** [vmware/tdnf#379]
### Describe the bug

I had a disk die on me with esxi.
Restored and ova from june 2022 based on photon 3

tdnsf distro-sync fails. 

I think the tdnf version is too old : tdnf: 2.1.0

Is there a way to wget the newest version or something? 

Another similar VW has tdnf 3.1.10  and there distrosync runs good.

### Reproduction steps

1. tdnf upgrade tdnf 
2.
3.
...

errors are:

Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64) Updates'
curl#7: Couldn't connect to server
Error: TDNFGetRepoMD 1208
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0 (x86_64) Updates' from 'https://packages.vmware.com/photon/3.0/photon_updates_3.0_x86_64'
Disabling Repo: 'VMware Photon Linux 3.0 (x86_64) Updates'

### Expected behavior

A smooth upgrade of all packages after which its back to the champagne life

**Comment by sshedi** [comment]
cc @oliverkurth

**Comment by oliverkurth** [comment]
This is most likely a network issue, so I would check that first. The URL is correct. Please try this command:

`curl -O https://packages.vmware.com/photon/3.0/photon_updates_3.0_x86_64/repodata/repomd.xml`

and show the result. If it fails, try to connect to other locations.

If it's really the tdnf version, you can download the latest version for Photon 3.0, then use `rpm` to install:
```
curl -O https://packages.vmware.com/photon/3.0/photon_updates_3.0_x86_64/x86_64/tdnf-3.1.10-1.ph3.x86_64.rpm
curl -O https://packages.vmware.com/photon/3.0/photon_updates_3.0_x86_64/x86_64/tdnf-cli-libs-3.1.10-1.ph3.x86_64.rpm
rpm -Uv ./tdnf-*.rpm
```

**Comment by hanscees** [comment]
> 

darn you were right: I did some port redirection on smtp ports but forgot it needs updates by port 443

However: now it says:

tdnf --debugsolver repolist
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64) Updates'
curl#60: Peer certificate cannot be authenticated with given CA certificates
Error: TDNFGetRepoMD 1261
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0 (x86_64) Updates' from 'https://packages.vmware.com/photon/3.0/photon_updates_3.0_x86_64'


However, after adjusting curl .curlrc with the [insecure] option curl downloads work

But then tdnf still failes:
Error(1261) : Peer certificate cannot be authenticated with given CA certificates

Where is the certificate store of tdnf or photon? Perhaps I can copy them form a working photon 3 host?

**Comment by hanscees** [comment]
I am giving up. Will build a new server

**Comment by oliverkurth** [comment]
tdnf does not have its own certificate store, it uses the one from the system (or whatever curl uses - tdnf uses libcurl). Newer tdnf versions have the `sslverify` option (for the repo configs, see https://github.com/vmware/tdnf/wiki/Repository-Configuration#sslverify). So if you update tdnf first as I described above it could work.

**Comment by oliverkurth** [comment]
Closing, issue mostly likely not related to tdnf.
