### ISSUE TITLE
tdnf 3.5.2 does not respect exclusions

### ISSUE THREAD

**Issue by aad-griff** [vmware/tdnf#426]
### Describe the bug

Complete a fresh install of Photon 5.0

```
echo 'exclude=dracut*' >> /etc/tdnf/tdnf.conf
tdnf update
```

tdnf marks dracut for update when it should not.

### Reproduction steps

1. Complete a fresh install of Photon 5.0
2. echo 'exclude=dracut*' >> /etc/tdnf/tdnf.conf
3. tdnf update
...

### Expected behavior

tdnf should respect exclusions in /etc/tdnf/tdnf.conf

**Comment by oliverkurth** [comment]
Thank you for reporting. I could reproduce this quickly in a container with `nss-libs`:
```
root [ ~ ]# echo 'exclude=nss-libs' >> /etc/tdnf/tdnf.conf 
root [ ~ ]# tdnf update                  

Upgrading:
nss-libs                               x86_64                       3.78-4.ph5                             photon-updates                 2.47M                         943.74k

Total installed size:   2.47M
Total download size: 943.74k
Is this ok [y/N]: N
Error(1032) : Operation aborted.
root [ ~ ]# 
```
However, it works on the command line:
```
root [ ~ ]# tdnf update --exclude=nss-libs
Nothing to do.
```

You may also consider using the 'lock' feature:
```
root [ ~ ]# mkdir -p /etc/tdnf/locks.d
root [ ~ ]# echo 'nss-libs' > /etc/tdnf/locks.d/nss-libs.conf
root [ ~ ]# tdnf update
Nothing to do.
root [ ~ ]# 
```

Not saying this isn't a bug (it is), but setting `dracut` as 'locked' may be what you want. It means that the package cannot be updated, downgraded or removed. See also https://github.com/vmware/tdnf/wiki/Configuration-Options#package-locks .

**Comment by oliverkurth** [comment]
LOL, there is no bug. The option is `excludepkgs`, not `exclude`. This works:
```
root [ ~ ]# echo 'excludepkgs=nss-libs' >> /etc/tdnf/tdnf.conf 
root [ ~ ]# tdnf update
Warning: The following packages are excluded from tdnf.conf:
  nss-libs

Installing:
glibc-libs                             x86_64                       2.36-5.ph5                             photon-updates                 4.46M                           1.60M

Total installed size:   4.46M
Total download size:   1.60M

Upgrading:
glibc                                  x86_64                       2.36-5.ph5                             photon-updates                 9.17M                           1.83M

Total installed size:   9.17M
Total download size:   1.83M
Is this ok [y/N]: N
Error(1032) : Operation aborted.
root [ ~ ]# 
```

I know, it's confusing. We didn't come up with this, it's the same in Fedora's `dnf` - the config setting is `excludepkgs`, the command line parameter is `exclude`.
