### ISSUE TITLE
tdnf distro-sync doesn't work

### ISSUE THREAD

**Issue by mattolenik** [vmware/tdnf#43]
...

```
$ tdnf distro-sync
No such command: distro-sync. Please use /usr/bin/tdnf --help
```

**Comment by ppadmavilasom** [comment]
This is available in TP2. Please update to tdnf-1.0.4 and try

**Comment by mattolenik** [comment]
Is that not what's available in the latest vmware/photo container on the Docker Hub? I'm running inside a container and hitting this. I even see "distro-sync" in the list of commands, but running it returns an error. It works on a TP2 VM I have.

**Comment by ppadmavilasom** [comment]
might not be TP2 on docker hub then. tdnf --version should tell you which version you have. distro-sync is enabled from 1.0.4 and upwards
