### ISSUE TITLE
Invalid Argument Error (1622) after a repo is disabled

### ISSUE THREAD

**Issue by sameluch** [vmware/tdnf#431]
### Describe the bug

Invalid Argument Error is received after a remote repo is disabled when trying to running `tdnf install -y <package>`, despite the package being available from another repository. This is functionality that was previously available, but has been removed in the latest version.

### Reproduction steps

1. On an ARM64 System, have a repository with the `skip_if_unavailable=True`
2. Run a tdnf install where the remote repository is unavailable, but the package is available from a local repo
3. see Invalid Argument error.

### Expected behavior

The disabled repo should not be queried as a part of the repo pool after being disabled for tdnf being unable to get the metadata file from a remote repo. And an Invalid Argument error should not be given.

### Additional context

This behavior was noticed originally on an ARM64 system, but the behavior _should_ be architecture independent.

Additionally this was noticed from upgrading from v3.2.2 to v3.5.2. The behavior change seems centered around the movement of TDNFGetRepoMD in repo.c from [this change](https://github.com/vmware/tdnf/commit/973238af74fd6860d78bc65d5bb9a5a720ce2599#diff-5fa811fd7755af32bbff3eb9a5a804ff192bbdde0a45b500c6177b4a47d548e0L60). When `TDNFGetRepoMD` fails following this change, the repo is left as a part of `pPool` while the repo gets disabled afterwards and the `whatprovides` array is not populated by `TDNFInitRepo`. The error comes from [this section](https://github.com/vmware/tdnf/blob/dev/solv/tdnfquery.c#L448) with a Null pointer on `pPool->whatprovides`.

**Comment by oliverkurth** [comment]
Thank you for the detailed analysis. I will have a look tomorrow.

**Comment by oliverkurth** [comment]
Fix is here: https://github.com/vmware/tdnf/pull/432

**Comment by sameluch** [comment]
Amazing, this is the same patch I had come up with in the meantime. Thank you so much for the quick response!
