### ISSUE TITLE
installonly_limit value not respected (removes running kernel)

### ISSUE THREAD

**Issue by rlmenge** [vmware/tdnf#436]
### Describe the bug

The `installonly_limit` value in `tdnf.conf` does not change the behavior of tdnf. Only 1 kernel and its modules are ever present. An upgrade/downgrade will remove all other kernels except the new kernel being installed. `rpm -ihv` and `dnf install -y` behave as expected,

ie. installonly_limit=3 should result in up to 3 kernels. However, all other kernels are always removed for the new kernel being installed. 

This option is mentioned in the [documentation ](https://github.com/vmware/tdnf/blob/dev/README.md)in the example tdnf.conf and config code 

### Reproduction steps
1. 
```
# confirm installonly_limit=3
cat /etc/tdnf/tdnf.conf 
```
2. 
```
tdnf install -y kernel-<different version>
```
3. 
```
# check that running kernel vmlinuz has been removed
 ls /boot
 ```
4.
``` 
# check that running kernel's modules have been removed (folder still present)
ls /lib/modules/$(uname -r)
```

### Expected behavior
1. 
```
# confirm installonly_limit=3
cat /etc/tdnf/tdnf.conf 
```
2.
```
tdnf install -y kernel-<different version>
```
3. 
```
# check that running kernel vmlinuz and new vmlinuz present
 ls /boot
 ```

**Comment by oliverkurth** [comment]
Thank you for reporting.

Looks like, sadly, the option is not implemented at all.

**Comment by rlmenge** [comment]
Thanks for checking into this! Are there plans to implement installonly_limit in the future?

**Comment by oliverkurth** [comment]
Feel free to checkout out PR #439 .
