### ISSUE TITLE
tdnf support for metalink ...

### ISSUE THREAD

**Issue by ppadmavilasom** [vmware/tdnf#63]
Re: vmware/photon#468

From @gregmmurray 
Can we add support for the metalink option to tdnf?

Getting some resilience in accessing repos and the ability to have some sophistication on which mirror/repo we direct users is important. There's potential, too, to improve security and validation of packages.

**Comment by Conan-Kudo** [comment]
If you're going to do that, you might as well also support signed repodata, too. The checking of repodata GPG signatures is controlled in DNF with `repo_gpgcheck` flag.

**Comment by oliverkurth** [comment]
This is resolved with https://github.com/vmware/tdnf/commit/31a577946b6286daf10c7af5f1b94f36a8b2e59f .
