### ISSUE TITLE
distroverpkg config entry is set to a package that is not installed

### ISSUE THREAD

**Issue by furlongm** [vmware/tdnf#64]
I get the below error after following the compile/install instructions in the readme. The error is not so clear, do you know what the issue is?

```
[root@centos cli]# ./tdnf list
Error(1022) : distroverpkg config entry is set to a package that is not installed. Check /etc/tdnf/tdnf.conf
```

**Comment by ppadmavilasom** [comment]
@furlongm tdnf assumes distroverpkg to be photon-release if not overridden in tdnf.conf. Please check if you have photon-release installed or override with --releasever
tdnf list --releasever 1.0

**Comment by furlongm** [comment]
Thanks, that gets me to the next error:

```
[root@centos tdnf]# ./tools/cli/tdnf --releasever 1.0 list
Error(1003) : Error loading tdnf repo (normally under /etc/yum.repos.d/)
```

**Comment by Conan-Kudo** [comment]
@ppadmavilasom You should set this to `system-release` instead, which is a generic Provides common to `redhat-release`, `fedora-release`, and `mageia-release`. Ideally, `photon-release` should have that Provides too.

**Comment by ppadmavilasom** [comment]
@Conan-Kudo it defaults to photon-release and runs into the issue reported when photon-release is not installed. then it can be overridden either by setting in tdnf.conf or passing in the releasever via cmd line.

**Comment by Conan-Kudo** [comment]
@ppadmavilasom I've submitted a PR to photon to add `system-release` Provides: https://github.com/vmware/photon/pull/963

Once that's merged in, then tdnf can just use `system-release` just like dnf does.

**Comment by oliverkurth** [comment]
Should be resolved now.
