### ISSUE TITLE
hawkey is deprecated, use libdnf instead

### ISSUE THREAD

**Issue by Conan-Kudo** [vmware/tdnf#66]
The upstream DNF project has deprecated the hawkey library, and has merged libhif and hawkey into libdnf. Please migrate to [libdnf](https://github.com/rpm-software-management/libhif).

See [this announcement](http://dnf.baseurl.org/2016/02/24/dnf-into-c-initiative-started/) for more information.

**Comment by ppadmavilasom** [comment]
@Conan-Kudo thanks for the info.

**Comment by jsilhan** [comment]
Also you can reuse rpm transaction, progress indicator, metadata and package downloading from libdnf. DNF-2.0 in Fedora rawhide is currently using libdnf.

**Comment by ppadmavilasom** [comment]
tdnf uses libsolv directly without the hawkey wrapper now (in dev and master branches).
