### ISSUE TITLE
tdnf distro-sync returned a non-zero code: 70

### ISSUE THREAD

**Issue by sergiosagu** [vmware/tdnf#69]
Hi,

When building [Admiral](https://github.com/vmware/admiral) container image based on vmware/photon:1.0 if we run "tdnf distro-sync --refresh -y" we get the following trace:

...
 ---> Running in 3e5311a68153
Refreshing metadata for: 'VMware Lightwave 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)Updates'
Refreshing metadata for: 'VMware Photon Extras 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)'

Installing:
libssh2                         x86_64      1.8.0-1.ph1         182.22 k

Total installed size: 182.22 k

Upgrading:
zlib                            x86_64      1.2.8-5.ph1         103.93 k
vim                             x86_64      7.4-9.ph1             1.93 M
util-linux                      x86_64      2.27.1-3.ph1          4.57 M
tdnf                            x86_64      1.1.0-1.ph1         134.56 k
tcsh                            x86_64      6.19.00-6.ph1       477.08 k
sqlite-autoconf                 x86_64      3.18.0-2.ph1          2.27 M
rpm                             x86_64      4.11.2-14.ph1         4.28 M
readline                        x86_64      6.3-5.ph1             3.52 M
photon-release                  noarch      1.0-6.ph1           474.00 b
pcre                            x86_64      8.39-1.ph1          960.35 k
openssl                         x86_64      1.0.2l-1.ph1          5.23 M
nss                             x86_64      3.31-1.ph1            3.88 M
nspr                            x86_64      4.15-1.ph1          951.07 k
ncurses                         x86_64      6.0-5.ph1             6.83 M
libgpg-error                    x86_64      1.27-1.ph1          700.45 k
libstdc++                       x86_64      5.3.0-4.ph1           1.56 M
libgcc                          x86_64      5.3.0-4.ph1         100.42 k
libassuan                       x86_64      2.4.3-1.ph1         106.00 k
glibc                           x86_64      2.22-13.ph1          50.98 M
filesystem                      x86_64      1.0-10.ph1            7.14 k
expat                           x86_64      2.2.0-1.ph1         242.58 k
elfutils-libelf                 x86_64      0.169-1.ph1         885.12 k
curl                            x86_64      7.54.0-1.ph1          1.35 M
bzip2                           x86_64      1.0.6-6.ph1           1.65 M
bash                            x86_64      4.3.30-10.ph1         2.50 M

Total installed size: 95.13 M

Reinstalling:
which                           x86_64      2.21-2.ph1           30.91 k
popt                            x86_64      1.16-2.ph1          119.44 k
pkg-config                      x86_64      0.28-2.ph1          554.22 k
photon-repos                    noarch      1.0-4.ph1             1.97 k
lua                             x86_64      5.3.2-2.ph1         612.17 k
libsolv                         x86_64      0.6.19-2.ph1          1.09 M
librepo                         x86_64      1.7.17-2.ph1        413.00 k
libffi                          x86_64      3.2.1-2.ph1          54.96 k
libcap                          x86_64      2.25-2.ph1           80.33 k
hawkey                          x86_64      2014.1-4.ph1        137.93 k
grep                            x86_64      2.21-2.ph1          719.41 k
gpgme                           x86_64      1.6.0-2.ph1         523.95 k
glib                            x86_64      2.47.6-2.ph1          2.97 M
findutils                       x86_64      4.6.0-2.ph1           1.62 M
file                            x86_64      5.24-2.ph1            3.85 M
db                              x86_64      6.1.26-2.ph1          4.42 M
coreutils                       x86_64      8.25-2.ph1            5.27 M
ca-certificates                 x86_64      20160109-5.ph1        1.80 M
attr                            x86_64      2.4.47-3.ph1        195.53 k

Total installed size: 24.39 M

Downloading:
libssh2                                  81299    100%
attr                                     82511    100%
ca-certificates                         836766    100%
coreutils                              2534896    100%
db                                     1976531    100%
file                                    301842    100%
findutils                               623785    100%
glib                                   1226180    100%
gpgme                                   225930    100%
grep                                    224018    100%
hawkey                                   51710    100%
libcap                                   42649    100%
libffi                                   29489    100%
librepo                                 140724    100%
libsolv                                 397795    100%
lua                                     292941    100%
photon-repos                              4523    100%
pkg-config                              227051    100%
popt                                     58622    100%
which                                    19231    100%
bash                                    888417    100%
bzip2                                   526008    100%
curl                                    967000    100%
elfutils-libelf                         308371    100%
expat                                    92851    100%
filesystem                               16590    100%
glibc                                 19395292    100%
libassuan                                48255    100%
libgcc                                   49103    100%
libstdc++                               479272    100%
libgpg-error                            218745    100%
ncurses                                1957223    100%
nspr                                    251586    100%
nss                                    1603945    100%
openssl                                3196457    100%
pcre                                    383441    100%
photon-release                            4196    100%
readline                               1645441    100%
rpm                                    1761793    100%
sqlite-autoconf                        1113964    100%
tcsh                                    279213    100%
tdnf                                     59886    100%
util-linux                             2049044    100%
vim                                    1046561    100%
zlib                                     60789    100%
Testing transaction
Found 32 problems
package pkg-config-0.28-2.ph1.x86_64 is already installed
package gpgme-1.6.0-2.ph1.x86_64 is already installed
package db-6.1.26-2.ph1.x86_64 is already installed
package ca-certificates-20160109-5.ph1.x86_64 is already installed
package libffi-3.2.1-2.ph1.x86_64 is already installed
package glib-2.47.6-2.ph1.x86_64 is already installed
package librepo-1.7.17-2.ph1.x86_64 is already installed
package file-5.24-2.ph1.x86_64 is already installed
package grep-2.21-2.ph1.x86_64 is already installed
package lua-5.3.2-2.ph1.x86_64 is already installed
package attr-2.4.47-3.ph1.x86_64 is already installed
package libcap-2.25-2.ph1.x86_64 is already installed
package coreutils-8.25-2.ph1.x86_64 is already installed
package popt-1.16-2.ph1.x86_64 is already installed
package libsolv-0.6.19-2.ph1.x86_64 is already installed
package hawkey-2014.1-4.ph1.x86_64 is already installed
package photon-repos-1.0-4.ph1.noarch is already installed
package findutils-4.6.0-2.ph1.x86_64 is already installed
package which-2.21-2.ph1.x86_64 is already installed
/sbin/ldconfig is needed by (installed) gpgme-1.6.0-2.ph1.x86_64
/sbin/ldconfig is needed by (installed) gmp-6.0.0a-3.ph1.x86_64
/sbin/ldconfig is needed by (installed) coreutils-8.25-2.ph1.x86_64
/sbin/ldconfig is needed by (installed) libffi-3.2.1-2.ph1.x86_64
/sbin/ldconfig is needed by (installed) glib-2.47.6-2.ph1.x86_64
/sbin/ldconfig is needed by (installed) file-5.24-2.ph1.x86_64
/sbin/ldconfig is needed by (installed) lua-5.3.2-2.ph1.x86_64
/sbin/ldconfig is needed by (installed) popt-1.16-2.ph1.x86_64
/sbin/ldconfig is needed by (installed) findutils-4.6.0-2.ph1.x86_64
/bin/sh is needed by (installed) librepo-1.7.17-2.ph1.x86_64
/bin/sh is needed by (installed) grep-2.21-2.ph1.x86_64
/bin/sh is needed by (installed) libsolv-0.6.19-2.ph1.x86_64
/bin/sh is needed by (installed) findutils-4.6.0-2.ph1.x86_64
Error(70) : (null)
The command '/bin/sh -c tdnf distro-sync --refresh -y &&     tdnf clean all && ...' returned a non-zero code: 70
make: *** [run] Error 70

Any help? Thanks!

**Comment by pstroia** [comment]
Can you share the image digest?
It seems non-reproducible with the latest image pulled from Docker Hub (sha256: 69d0ce9a0ec...)

**Comment by sergiosagu** [comment]
Yes, could be. I saw the issue using an "old" host to build the image and maybe it was polluted somehow. I tried later using a brand new host and the build (and distro dependencies updates) was just fine. Closing the issue. Thanks!
