### ISSUE TITLE
tdnf add powershell package

### ISSUE THREAD

**Issue by DaBeOps** [vmware/tdnf#71]
May we add Powershell? It was included in PhotonOS v1 but not in the latest release. 

In order to increase the efficiency of PowerCLI(https://hub.docker.com/r/vmware/powerclicore/) it could be nice to add the latest release: https://github.com/PowerShell/PowerShell/releases.

**Comment by ppadmavilasom** [comment]
powershell is now available in PhotonOS 2.0. for further PhotonOS questions, please use https://github.com/vmware/photon
