### ISSUE TITLE
Does tdnf support retry/resume on failure?

### ISSUE THREAD

**Issue by ipetkov7** [vmware/tdnf#75]
On download failure, does the tool automatically retry from the bits it has successfully got (HTTP range requests)?
If yes, are the retry_count and retry_interval customizable?

**Comment by ppadmavilasom** [comment]
@ipetkov7 there is no auto retry atm

**Comment by ipetkov7** [comment]
Thanks @ppadmavilasom 
If run the tool after connection failure, will it request the package from the beginning or will resume it?

**Comment by ppadmavilasom** [comment]
it will request new as it removes the downloaded rpms on completion / error

**Comment by ipetkov7** [comment]
Thanks
