### ISSUE TITLE
How to make reposync for photon repository

### ISSUE THREAD

**Issue by daydrim** [vmware/tdnf#79]
Hello

Is there any way to create reposync (and sync changes periodically) for Photon OS 2 (and 1) repositories to use Photon only in local network environment with limited Internet access?

**Comment by oliverkurth** [comment]
This is going to be addressed with https://github.com/vmware/tdnf/pull/233 . Note that this change won't make it to Photon 1 or 2 though.

**Comment by oliverkurth** [comment]
The feature has been implemented. https://github.com/vmware/tdnf/pull/233 has been merged.
