### ISSUE TITLE
"remove" doesn't remove a package's dependencies

### ISSUE THREAD

**Issue by awwithro** [vmware/tdnf#81]
per the wiki 

> remove: This command removes a package. When removing a package, tdnf by default also removes 
> dependencies that are no longer used if they were was installed by tdnf as a dependency without
> being explicitly requested by a user. You can modify the dependency removal by changing the 
> clean_requirements_on_remove option in /etc/tdnf/tdnf.conf to false.

Running in a fresh container I see the following
```
root [ / ]# tdnf --version
tdnf: 2.0.0
```

``` 
root [ / ]# cat /etc/tdnf/tdnf.conf
[main]
gpgcheck=1
installonly_limit=3
clean_requirements_on_remove=true
repodir=/etc/yum.repos.d
cachedir=/var/cache/tdnf

root [ / ]# tdnf list installed |wc -l
32

root [ / ]# tdnf install git -y
...
root [ / ]# tdnf list installed |wc -l
65

root [ / ]# tdnf -y remove git

Removing:
git                                                         x86_64                        2.19.0-2.ph3                            @System                           20.88M 21895454

Total installed size:  20.88M 21895454
Testing transaction
Running transaction
Removing: git-2.19.0-2.ph3.x86_64

Complete!
root [ / ]# tdnf list installed |wc -l
64
```

I would expect the installed package count to be back to 32 with git and all of its dependencies removed

**Comment by oliverkurth** [comment]
Fixed with PR #283
