### ISSUE TITLE
cURL headers append callout

### ISSUE THREAD

**Issue by imayorski** [vmware/tdnf#82]
Can we provide callouts to curl calls in order to be able to append headers and provide ssl certificates?

**Comment by ppadmavilasom** [comment]
Hello. 
Please take a look at  https://github.com/vmware/tdnf/blob/master/client/remoterepo.c#L131 which calls TDNFRepoApplyProxySettings. You will have to do something similar. 
If you intent to provide callback to a program that links against libtdnf, you will need a way to set the callback into  tdnf handle. One way is to use it via https://github.com/vmware/tdnf/blob/master/include/tdnftypes.h#L177 as a new opt.

**Comment by oliverkurth** [comment]
Certificates is addressed with https://github.com/vmware/tdnf/pull/176 .

**Comment by oliverkurth** [comment]
Closing this issue. Certificates is addresses.
