### ISSUE TITLE
tdnf 1.2.3 stops and updates docker, but doesnt start it again 

### ISSUE THREAD

**Issue by hanscees** [vmware/tdnf#83]
Hi,
my docker demon stopped working. 

heres the relevant log
Feb 17 04:12:16 dns2019 [RPM][27370]: erase docker-18.06.1-1.ph2.x86_64: success
Feb 17 04:12:16 dns2019 systemd[1]: Stopping Docker Application Container Engine...
Feb 17 04:12:16 dns2019 dockerd[299]: time="2019-02-17T04:12:16.639847805+01:00" level=info msg="Processing signal 'terminated'"

... some more logging

Feb 17 04:12:21 dns2019 systemd[1]: Stopped Docker Application Container Engine.
Feb 17 04:12:23 dns2019 [RPM][27370]: install docker-18.06.2-1.ph2.x86_64: success
Feb 17 04:12:24 dns2019 [RPM][27370]: erase docker-18.06.1-1.ph2.x86_64: success
Feb 17 04:12:24 dns2019 [RPM][27370]: install docker-18.06.2-1.ph2.x86_64: success
Feb 17 04:12:24 dns2019 [RPM][27370]: install docker-18.06.2-1.ph2.x86_64: success
Feb 17 10:03:47 dns2019 systemd[1]: Starting Docker Application Container Engine...

I restarted it manually in the morning as you can see.
Why wouldnt it restart it after an update?

root@dns2019 [ ~ ]# /usr/bin/tdnf --version
tdnf: 1.2.3

systemctl status docker
docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-02-17 10:03:47 CET; 22min ago

**Comment by ppadmavilasom** [comment]
this might require a change in docker's rpm spec. please check with photon if not resolved.

**Comment by hanscees** [comment]
> this might require a change in docker's rpm spec. please check with photon if not resolved.

I am not sure what you want me to do? Check with photon? How?

**Comment by ppadmavilasom** [comment]
sorry i meant opening an issue with https://github.com/vmware/photon
docker-18.06.2-1.ph2.x86_64 you install should have post install scripts to restart docker if it was running at the time of upgrade. if this is not the case, photon specs should change to fix this.
