### ISSUE TITLE
tdnf check-update must return error for invalid package name argument

### ISSUE THREAD

**Issue by sidcha** [vmware/tdnf#88]
The 3rd argument is must either be empty or valid. Other cases must respond with suitable error message and code.

**Comment by oliverkurth** [comment]
If I understand correctly this is no longer an issue:
```
# tdnf -y install foolbar && echo yes
Error(1011) : No matching packages
root [ /build/build ]# 
```
I wasn't able to find any invalid command that returns a zero exit code. Please reopen if I am missing something.
