### ISSUE TITLE
Always return "Error(XXX)" as the first line of an error message for ease of parsing

### ISSUE THREAD

**Issue by sidcha** [vmware/tdnf#93]
After some research, I figured that there is no straightforward way to get the 32-bit return code from tdnf process across operating systems in a reliable way. For this reason, I switched to parsing the the stderr outputs with a regex like: `^Error\(\d+\)`. Now for this to work, we must always return the first line of any error message with the `Error(XXX)` message and be consistent about it.

###  Known deviants:
* `tdnf erase invalid_package`
* `tdnf install invalid_package`
* `tdnf update invalid_package`

**Comment by ppadmavilasom** [comment]
the lower 8 bits shows up as the exit code. tdnf should not return an exit code greater than 255. formatting error messages to enable reliable parsing is the right thing to do. lets fix the format for the ones that doesnt follow the majority and change the return code to just 1 for tdnf specific errors.

**Comment by sidcha** [comment]
> the lower 8 bits shows up as the exit code

Mostly yes. But when I did some search I found that `waitid()` must return all 32 bits according the 2016 edition of POSIX. Unfortunately, Linux doesn't do this (I haven't tried on BSD but I heard it works there). Nevertheless, we cannot rely on it.

**Comment by sidcha** [comment]
@keerthanakalyan, when your change #170 with re.search and re.NEWLINE gets merged, we can close this.
