### ISSUE TITLE
Return "Nothing to be done" when there are no packages to be upgraded

### ISSUE THREAD

**Issue by sidcha** [vmware/tdnf#94]
Currently, `tdnf list upgrades` returns an error code where there is no packages to be upgrades. While there may not be any package to be upgraded, the command itself is properly constructed and shouldn't return an error.

Something like "Nothing to be done here" is suitable alternative.

**Comment by ppadmavilasom** [comment]
agree

**Comment by oliverkurth** [comment]
This seems to be fixed:

```
root [ / ]# ./bin/tdnf list upgrades && echo yes
yes
root [ / ]#
```

**Comment by oliverkurth** [comment]
Hm, issue is still there:
```
# ./bin/tdnf list upgrades
Refreshing metadata for: 'VMware Photon Linux 4.0 (x86_64)'
Refreshing metadata for: 'VMware Photon Linux 4.0 (x86_64) Updates'
Refreshing metadata for: 'VMware Photon Extras 4.0 (x86_64)'
Error(1011) : No matching packages         123   100%
```

**Comment by oliverkurth** [comment]
Fixed.

**Comment by sidcha** [comment]
Finally, Yay! thanks @oliverkurth :)
