### ISSUE TITLE
Stream pointer might be NULL

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [vmware/tdnf#97]
'pCacheFile  ' is defined here, but may be NULL
https://github.com/vmware/tdnf/blob/94955ca8e66eb17a98bc3bf2ced9fcac6f2db86a/solv/tdnfrepo.c#L253
Stream pointer might be NULL
https://github.com/vmware/tdnf/blob/94955ca8e66eb17a98bc3bf2ced9fcac6f2db86a/solv/tdnfrepo.c#L257

**Comment by ppadmavilasom** [comment]
pCacheFile null check is already addressed in #95 

repo_add_rpmdb_reffp can handle null fp. no fix required as there are paths in tdnfrepo.c that need this.
see - https://github.com/openSUSE/libsolv/blob/e04f3016c49b0426cd822d5ba3259c6ab94c1181/ext/repo_rpmdb.c#L1830
